wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.11
    start_time: 1704684401.232676
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 13
      - 23
      4: 3.8.11
      5: 0.13.9
      8:
      - 5
